# Generated by Django 3.2.8 on 2021-10-11 18:45
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rubric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
                (
                    "order",
                    models.SmallIntegerField(
                        db_index=True, default=0, verbose_name="Порядок"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubRubric",
            fields=[],
            options={
                "verbose_name": "Подрубрика",
                "verbose_name_plural": "Подрубрики",
                "ordering": (
                    "super_rubric__order",
                    "super_rubric__name",
                    "order",
                    "name",
                ),
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("bboard.rubric",),
        ),
        migrations.CreateModel(
            name="SuperRubric",
            fields=[],
            options={
                "verbose_name": "Надрубрика",
                "verbose_name_plural": "Надрубрики",
                "ordering": ("order", "name"),
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("bboard.rubric",),
        ),
        migrations.AddField(
            model_name="rubric",
            name="super_rubric",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="bboard.superrubric",
                verbose_name="Надрубрика",
            ),
        ),
    ]
